<?php
//----------------------------------------------------------------------
//  CrawlTrack 3.3.0
//----------------------------------------------------------------------
// Crawler Tracker for website
//----------------------------------------------------------------------
// Author: Jean-Denis Brun
//----------------------------------------------------------------------
// Website: www.crawltrack.net
//----------------------------------------------------------------------
// That script is distributed under GNU GPL license
//----------------------------------------------------------------------
// file: searchenginelist.php
//----------------------------------------------------------------------
//file base on SearchEngines.php file of phpMyVisites V2
/*
 * phpMyVisites : website statistics and audience measurements
 * Copyright (C) 2002 - 2006
 * http://www.phpmyvisites.net/
 * phpMyVisites is free software (license GNU/GPL)
 * Authors : phpMyVisites team and community
*/
//----------------------------------------------------------------------
//  Last update: 07/04/2011
//----------------------------------------------------------------------
$crawltcssaattack = array("http:", "ftp:", "https:", "http%3a", "https%3a", "ht%20tp:", "htt%20p:", "http%20:", "h%20ttp:", "/etc/passwd", "ShellAdresi.TXT", "[evil_root]?", "http%3A%2F%2F","%68%74%74%70%3a","%68%74%74%70%73%3a","%48%54%54%50%3a","%48%54%54%50%53%3a","%3C?");
$crawltsqlaattack = array("%20select%20", "%20like%20", "%20or%20", "%20where%20","%20SELECT%20", "%20LIKE%20", "%20OR%20", "%20WHERE%20");
$crawltgooglelist = array(
"www.google.fr",
"www.google.ae",
"www.google.am",
"www.google.as",
"www.google.at",
"www.google.az",
"www.google.be",
"www.google.bg",
"www.google.ba",
"www.google.bi",
"www.google.bj",
"www.google.bs",
"www.google.ca",
"www.google.cat",
"www.google.cc",
"www.google.cd",
"www.google.cg",
"www.google.ch",
"www.google.ci",
"www.google.cl",
"www.google.cm",
"www.google.cn",
"www.google.co",
"www.google.cz",
"www.google.de",
"www.google.dj",
"www.google.dk",
"www.google.dm",
"www.google.dz",
"www.google.ee",
"www.google.es",
"www.google.fi",
"www.google.fm",
"www.google.gg",
"www.google.ge",
"www.google.gl",
"www.google.gm",
"www.google.gp",
"www.google.gr",
"www.google.hn",
"www.google.hr",
"www.google.ht",
"www.google.hu",
"www.google.ie",
"www.google.im",
"www.google.is",
"www.google.it",
"www.google.jo",
"www.google.kz",
"www.google.la",
"www.google.li",
"www.google.lk",
"www.google.lt",
"www.google.lu",
"www.google.lv",
"www.google.mg",
"www.google.mn",
"www.google.ms",
"www.google.mu",
"www.google.mw",
"www.google.md",
"www.google.nl",
"www.google.no",
"www.google.pl",
"www.google.sk",
"www.google.pn",
"www.google.ps",
"www.google.pt",
"www.google.dk",
"www.google.ro",
"www.google.rs",
"www.google.ru",
"www.google.rw",
"www.google.se",
"www.google.sn",
"www.google.sh",
"www.google.si",
"www.google.sm",
"www.google.td",
"www.google.tk",
"www.google.to",
"www.google.tp",
"www.google.tt",
"www.google.uz",
"www.google.vg",
"www.google.ws",
"www.google.com.ag",
"www.google.com.ai",
"www.google.com.ar",
"www.google.com.au",
"www.google.com.bd",
"www.google.com.bh",
"www.google.com.bn",
"www.google.com.bo",
"www.google.com.br",
"www.google.com.by",
"www.google.com.bz",
"www.google.com.co",
"www.google.com.cu",
"www.google.com.ec",
"www.google.com.eg",
"www.google.com.do",
"www.google.com.fj",
"www.google.com.gh",
"www.google.com.gr",
"www.google.com.gt",
"www.google.com.hk",
"www.google.com.jm",
"www.google.com.kh",
"www.google.com.kw",
"www.google.com.lb",
"www.google.com.ly",
"www.google.com.mt",
"www.google.com.mx",
"www.google.com.my",
"www.google.com.nf",
"www.google.com.ng",
"www.google.com.ni",
"www.google.com.np",
"www.google.com.pa",
"www.google.com.pe",
"www.google.com.ph",
"www.google.com.pk",
"www.google.com.pl",
"www.google.com.pr",
"www.google.com.py",
"www.google.com.qa",
"www.google.com.om",
"www.google.com.ru",
"www.google.com.sg",
"www.google.com.sa",
"www.google.com.sv",
"www.google.com.tr",
"www.google.com.tw",
"www.google.com.ua",
"www.google.com.uy",
"www.google.com.vc",
"www.google.com.vn",
"www.google.co.bw",
"www.google.co.ck",
"www.google.co.cr",
"www.google.co.gg",
"www.google.co.hu",
"www.google.co.id",
"www.google.co.il",
"www.google.co.in",
"www.google.co.je",
"www.google.co.jp",
"www.google.co.ls",
"www.google.co.ke",
"www.google.co.kr",
"www.google.co.nz",
"www.google.co.th",
"www.google.co.tz",
"www.google.co.ug",
"www.google.co.uk",
"www.google.co.uz",
"www.google.co.ve",
"www.google.co.yu",
"www.google.co.za",
"www.google.co.ma",
"www.google.co.zw",
"www.google.com",
);

$crawltmsnlist = array(
"www.live.com",
"beta.search.live.com",
"beta.search.msn.com",
"search.live.com",
"search.msn.fr",
"search.msn.es",
"search.msn.se",
"search.latam.msn.com",
"search.msn.nl",
"search.msn.co.jp",
"search.msn.no",
"search.msn.at",
"search.msn.com.hk",
"search.msn.com.ph",
"search.t1msn.com.mx",
"fr.ca.search.msn.com",
"search.msn.be",
"search.fr.msn.be",
"search.msn.it",
"search.msn.com.tw",
"search.msn.de",
"search.msn.co.uk",
"search.msn.co.za",
"search.msn.ch",
"search.msn.es",
"search.msn.com.br",
"search.ninemsn.com.au",
"search.msn.dk",
"search.arabia.msn.com",
"search.msn.com",
"search.prodigy.msn.com",
"search.msn.com.tr",
"search.msn.co.id",
"search.msn.com.sg",
"ie.search.msn.com",
"www.bing.com",
"cn.bing.com",
);

$crawltyahoolist = array(
"ink.yahoo.com",
"ink.yahoo.fr",
"fr.ink.yahoo.com",
"search.yahoo.co.jp",
"search.yahoo.fr",
"ar.search.yahoo.com",
"br.search.yahoo.com",
"de.search.yahoo.com",
"ca.search.yahoo.com",
"cf.search.yahoo.com",
"dk.search.yahoo.com",
"fr.search.yahoo.com",
"espanol.search.yahoo.com",
"es.search.yahoo.com",
"hk.search.yahoo.com",
"id.search.yahoo.com",
"in.search.yahoo.com",
"it.search.yahoo.com",
"kr.search.yahoo.com",
"mx.search.yahoo.com",
"nl.search.yahoo.com",
"uk.search.yahoo.com",
"cade.search.yahoo.com",
"tw.search.yahoo.com",
"vn.search.yahoo.com",
"www.yahoo.com.cn",
"search.yahoo.com",
"search.cn.yahoo.com",
"kr.dist.search.yahoo.com",
);

$crawltasklist = array(
"web.ask.com",
"www.ask.co.uk",
"au.ask.com",
"uk.ask.com",
"fr.ask.com",
"de.ask.com",
"es.ask.com",
"it.ask.com",
"nl.ask.com",
"ask.jp",
"www.ask.com",
);
//exalead list no more used in 3.2.0
$crawltexaleadlist = array(
"www.exalead.com",
"www.exalead.fr",
);

$crawltbaidulist = array(
"www.baidu.com",
);

$crawltbrowserlist = array(
//Chrome
"Chrome",
//Firefox
"Firefox",
//Internet explorer-windows 98
"compatible; MSIE 5.0; Windows 98;",
"compatible; MSIE 5.01; Windows 98;",
"compatible; MSIE 5.5; Windows 98;",
"compatible; MSIE 6.0; Windows 98;",
//Internet explorer-windows 2000
"compatible; MSIE 5.01; Windows NT 5.0;",
"compatible; MSIE 5.5; Windows NT 5.0;",
"compatible; MSIE 6.0; Windows NT 5.0;",
//Internet explorer-windows XP
"compatible; MSIE 6.0; Windows NT 5.1;",
"compatible; MSIE 7.0; Windows NT 5.1;",
"compatible; MSIE 8.0; Windows NT 5.1;",
//Internet explorer-windows Vista
"compatible; MSIE 7.0; Windows NT 6.0;",
"compatible; MSIE 8.0; Windows NT 5.2;",
"compatible; MSIE 8.0; Windows NT 6.0;",
"compatible; MSIE 9.0; Windows NT 6.0;",
//Internet explorer-windows Seven
"compatible; MSIE 7.0; Windows NT 6.1;",
"compatible; MSIE 8.0; Windows NT 6.1;",
"compatible; MSIE 9.0; Windows NT 6.1;",
//Internet explorer pocket
"compatible; MSIE 4.01; Windows CE;",
//PlayStation
"PlayStation Portable",
//others
"Opera",
"Safari",
"OmniWeb",
"BrowseX",
"MultiZilla",
"SeaMonkey",
"K-meleon",
"Camino",
"Konqueror",
);

$crawltbrowserlist2 = array(
"0" => "??",
//Chrome
"1" => "Chrome",
//Firefox
"2" => "Firefox",
//Internet explorer
"3" => "Internet Explorer 5",
"4" => "Internet Explorer 6",
"5" => "Internet Explorer 7",
"6" => "Internet Explorer 8",
//Internet explorer pocket
"7" => "Internet explorer pocket",
//PlayStation
"8" => "PlayStation Portable",
//others
"9" => "Opera",
"10" => "Safari",
"11" => "OmniWeb",
"12" => "BrowseX",
"13" => "MultiZilla",
"14" => "SeaMonkey",
"15" => "K-meleon",
"16" => "Camino",
"17" => "Konqueror",
"18" => "Safari iPhone",
"19" => "Safari iPod Touch",
"20" => "Safari Android",
"21" => "Safari Nokia",
"22" => "Opera Mini",
"23" => "Safari iPad",
"24" => "Internet Explorer 9",
);


$crawltnonebrowserlist = array(
"bsalsa.com",
"HTTrack",
"MemoWeb",
"AspiWeb",
"OutWit",
"Wget",
"cURL",
"Webcopier",
"AntivirXP08",
"Zango",
"Robot",
"iOpus",
"FunWebProducts",
"AMD64",
"Win64",
"Jakarta",
);

?>
